### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Naveena-007**

### CODE REVIEW

**Comment by Naveena-007** [comment]
Created a new issue [correct index page is not visible #4](https://github.com/fssa-batch3/naveenasri.nagarajan__web_project/issues/4) in GitHub

**Comment by Naveena-007** [comment]
Created a new issue [Password correction #5](https://github.com/fssa-batch3/naveenasri.nagarajan__web_project/issues/5) in GitHub

**Comment by Naveena-007** [comment]
Created a new issue [design creation #6](https://github.com/fssa-batch3/naveenasri.nagarajan__web_project/issues/6) in GitHub

**Comment by Ajmal112** [comment]
Created a new issue [Password Pattern Issue  #7](https://github.com/fssa-batch3/naveenasri.nagarajan__web_project/issues/7) in GitHub

**Comment by Ajmal112** [comment]
Created a new issue [User Profile Issue #8](https://github.com/fssa-batch3/naveenasri.nagarajan__web_project/issues/8) in GitHub

**Comment by Ajmal112** [comment]
Created a new issue [Password Show Issue #9](https://github.com/fssa-batch3/naveenasri.nagarajan__web_project/issues/9) in GitHub

**Comment by Ajmal112** [comment]
Created a new issue [Password Show Issue #10](https://github.com/fssa-batch3/naveenasri.nagarajan__web_project/issues/10) in GitHub

**Comment by Ajmal112** [comment]
Created a new issue [Architect Password Issue #11](https://github.com/fssa-batch3/naveenasri.nagarajan__web_project/issues/11) in GitHub

**Comment by Ajmal112** [comment]
Created a new issue [Validation Issue #12](https://github.com/fssa-batch3/naveenasri.nagarajan__web_project/issues/12) in GitHub

**Comment by Ajmal112** [comment]
Created a new issue [Create Design Issue  #13](https://github.com/fssa-batch3/naveenasri.nagarajan__web_project/issues/13) in GitHub

**Comment by Ajmal112** [comment]
Created a new issue [Edit Design Issue #14](https://github.com/fssa-batch3/naveenasri.nagarajan__web_project/issues/14) in GitHub

**Comment by lakshmipriyasundarraj** [comment]
Created a new issue [experience #15](https://github.com/fssa-batch3/naveenasri.nagarajan__web_project/issues/15) in GitHub

**Comment by lakshmipriyasundarraj** [comment]
Created a new issue [booking Architecture  #16](https://github.com/fssa-batch3/naveenasri.nagarajan__web_project/issues/16) in GitHub

**Comment by lakshmipriyasundarraj** [comment]
Created a new issue [names should contains only space #17](https://github.com/fssa-batch3/naveenasri.nagarajan__web_project/issues/17) in GitHub

**Pull request merged**
